### ISSUE TITLE
Include alpha version changelog in the final version

### ISSUE THREAD

**Issue by njfamirm** [lerna-lite/lerna-lite#952] opened 2024-10-20 07:41 UTC
### Clear and concise description of the problem

Hi

When I'm release many alpha version and then final version, the changelog (in github and other place) not include alpha version

### Suggested solution

include all alpha changes in final version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment] 2024-10-20 14:20
When you use conventional changelog, all these changelogs are created by 3rd party library [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages) not by Lerna itself. You also did not provide any repro and I did alpha releases in the past and never had any problems, so this issue will be closed unless you provide a full repro

**Comment by njfamirm** [comment] 2024-10-21 04:50
> When you use conventional changelog, all these changelogs are created by 3rd party library [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages) not by Lerna itself. You also did not provide any repro and I did alpha releases in the past and never had any problems, so this issue will be closed unless you provide a full repro

This is my changelog

```md
## [6.9.3](https://github.com/njfamirm/soffit-order/compare/v6.9.2...v6.9.3) (2024-10-20)

### Bug Fixes

* **app/send-otp:** enable sitemap ([c6defec](https://github.com/njfamirm/soffit-order/commit/c6defec8c37aaa305d4b1697be10ff5a55000238)) by @

## [6.9.2](https://github.com/njfamirm/soffit-order/compare/v6.9.1...v6.9.2) (2024-10-20)

### Miscellaneous Chores

* correct color theme based logo changes ([7618244](https://github.com/njfamirm/soffit-order/commit/76182443d10b1da16c0604cc8f32c01c90d502b6)) by @

## [6.9.1](https://github.com/njfamirm/soffit-order/compare/v6.9.0...v6.9.1) (2024-10-20)

### Bug Fixes

* **app/robots:** allow sign in send otp page ([338ff1b](https://github.com/njfamirm/soffit-order/commit/338ff1b412fd90dcaa469fffa463ccfe8e74cfb0)) by @

### Miscellaneous Chores

* add release info ([f3af625](https://github.com/njfamirm/soffit-order/commit/f3af625a2bc1c5dadc681f057b1532cbab930e89)) by @

## [6.9.0](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.9...v6.9.0) (2024-10-20)

**Note:** Version bump only for package @alwatr/order-app

## [6.9.0-alpha.9](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.8...v6.9.0-alpha.9) (2024-10-20)

**Note:** Version bump only for package @alwatr/order-app

## [6.9.0-alpha.8](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.7...v6.9.0-alpha.8) (2024-10-20)

### Bug Fixes

* add __dev_mode__ for package tracer ([01e9d40](https://github.com/njfamirm/soffit-order/commit/01e9d40f90f485059794b09274df07fbf2020646)) by @njfamirm
* use /* @__PURE__ */ for non side effect parts ([a119fca](https://github.com/njfamirm/soffit-order/commit/a119fca8c76bbe45abba45d36595355ffa8e2b5f)) by @njfamirm

## [6.9.0-alpha.7](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.6...v6.9.0-alpha.7) (2024-10-20)

### Features

* **common/theme-builder:** fucking awesome custom color support ([db31d55](https://github.com/njfamirm/soffit-order/commit/db31d5573e4a9c74e91975a732e37ee2745ac385)) by @njfamirm
* **pwa:** enhance install process ([c38d039](https://github.com/njfamirm/soffit-order/commit/c38d0390617e21864c0b58d443df35045ba678f9)) by @njfamirm

### Code Refactoring

* use custom green color ([47aa84d](https://github.com/njfamirm/soffit-order/commit/47aa84d1780bd7b7b02306424a4452ddd2deae65)) by @njfamirm

### Miscellaneous Chores

* rename function ([479babf](https://github.com/njfamirm/soffit-order/commit/479babf55f3217ea241eea1f4d99b196b2d1d591)) by @njfamirm

## [6.9.0-alpha.6](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.5...v6.9.0-alpha.6) (2024-10-20)

### Features

* **app:** Added summary page to review orders ([e8b3ea6](https://github.com/njfamirm/soffit-order/commit/e8b3ea64213e0ad7c10c0f9a86430288f0118514)) by @arashagp

### Bug Fixes

* **app/cart:** don't watch for hash change on child mode ([9537550](https://github.com/njfamirm/soffit-order/commit/953755095cd0fdd37f9192cf642954ecb756e52a)) by @njfamirm
* **app/orders/draft/summary:** correct machine ([401e200](https://github.com/njfamirm/soffit-order/commit/401e2002d1ec96b4c743cad7510b062464ab3530)) by @njfamirm
* **app/orders/draft:** remove extra padding ([53af300](https://github.com/njfamirm/soffit-order/commit/53af3000d908f110945de6d2522f2e38b1f37a6f)) by @njfamirm
* **app:** undo to functionally submit function ([de9c451](https://github.com/njfamirm/soffit-order/commit/de9c451df4ef8811edd0263a6227006cb246f622)) by @arashagp

### Code Refactoring

* **app/draft/summary:** move submit order to fab ([ad2a233](https://github.com/njfamirm/soffit-order/commit/ad2a2339408330c5f50f96625e7eb4b84df5ee04)) by @njfamirm
* **app/orders/summary:** remove extra parts ([ee63eee](https://github.com/njfamirm/soffit-order/commit/ee63eee4f336344b1d5ae3030d99090191d12c31)) by @njfamirm
* **app/shipping-info:** remove unnecessary comment's ([ded4612](https://github.com/njfamirm/soffit-order/commit/ded4612f2970e39ab34c3f293571146a134a13f4)) by @arashagp
* **app/summary:** change some of the store  state to correct store state ([c2b6d25](https://github.com/njfamirm/soffit-order/commit/c2b6d25dacf5d1ee98a8ecae684864b4bd2c7c40)) by @arashagp
* **app:** commented some of options for summary ([7f7f784](https://github.com/njfamirm/soffit-order/commit/7f7f78428846b0826259fa2abbfc65478af46efa)) by @arashagp

### Miscellaneous Chores

* formatting and building directory ([54eeb4e](https://github.com/njfamirm/soffit-order/commit/54eeb4e5cbd32711d006c137cf1d65eee63b6a4f)) by @arashagp

## [6.9.0-alpha.5](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.4...v6.9.0-alpha.5) (2024-10-17)

### Bug Fixes

* add url to robots ([f8b7faf](https://github.com/njfamirm/soffit-order/commit/f8b7faf39b5ff42162d8d168a08271565e9419a0)) by @njfamirm
* **app/install-pwa-guide:** top padding ([2c65e0a](https://github.com/njfamirm/soffit-order/commit/2c65e0a44a28817f85ef88de9244df4ab473867f)) by @njfamirm

### Code Refactoring

* remove car type from shipping info ([6f70733](https://github.com/njfamirm/soffit-order/commit/6f70733d2d7b825bb6b91251079b7592da3bec93)) by @njfamirm

## [6.9.0-alpha.4](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.3...v6.9.0-alpha.4) (2024-10-16)

### Features

* **app:** support old link ([0247aee](https://github.com/njfamirm/soffit-order/commit/0247aee91666c2e352f7ecad29bdc0360cbdc5bf)) by @

## [6.9.0-alpha.3](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.2...v6.9.0-alpha.3) (2024-10-16)

**Note:** Version bump only for package @alwatr/order-app

## [6.9.0-alpha.2](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.1...v6.9.0-alpha.2) (2024-10-16)

### Bug Fixes

* review issue ([a12aaf3](https://github.com/njfamirm/soffit-order/commit/a12aaf32450c33a54e5cddae1724078c09996267)) by @

## [6.9.0-alpha.1](https://github.com/njfamirm/soffit-order/compare/v6.9.0-alpha.0...v6.9.0-alpha.1) (2024-10-16)

### Bug Fixes

* reported sign in issue ([f0a1710](https://github.com/njfamirm/soffit-order/commit/f0a1710e846224f78cf02d42124a7bc9327157f4)) by @

## [6.9.0-alpha.0](https://github.com/njfamirm/soffit-order/compare/v6.8.3...v6.9.0-alpha.0) (2024-10-16)

### Features

* **api/api-server-util:** require token ([f151988](https://github.com/njfamirm/soffit-order/commit/f15198808aca402edd38c29a8f13272b09100991)) by @njfamirm
* **api:** fucking sign in with otp ([3d4c080](https://github.com/njfamirm/soffit-order/commit/3d4c0805e1f1fe4fa28e1fd7f5fbc32e1ad91bd0)) by @njfamirm
* **app/install-guide:** support more browser ([12ecff8](https://github.com/njfamirm/soffit-order/commit/12ecff88b29f9d522c2c626005522ceaefb40ce2)) by @arashagp
* **app/install-pwa-guide:** put safari info ([f396484](https://github.com/njfamirm/soffit-order/commit/f396484fd52187d453c11a132d3fa36f1862b51b)) by @njfamirm
* **app/sign-in:** handle before signed in ([fbc9160](https://github.com/njfamirm/soffit-order/commit/fbc9160ecbe096691a671423cbc4d414b05815e6)) by @njfamirm
* **app:** add isValid variable for property errorHandler inputs, change title of the inputs and buttons ([ebc78b8](https://github.com/njfamirm/soffit-order/commit/ebc78b8b65fad6bcc4b4fdaa75b8224361c5108e)) by @arashagp
* **app:** structure of validating with phone number ([b9d67bb](https://github.com/njfamirm/soffit-order/commit/b9d67bb5ae07c0c6024fa946e3f750a846ea3691)) by @arashagp
* **app:** write and change structure of validating user with phone number, add one more machine, one more page and one more request ([877d479](https://github.com/njfamirm/soffit-order/commit/877d4793dcdb3cc181df1a18ed80402d9b959e7c)) by @arashagp
```

**Comment by ghiscoding** [comment] 2024-10-21 13:29
That is how conventional-changelog create the changelogs and commits are only visited once and will never be revisited more than once even if it's alpha. That's also not a Lerna/Lerna-Lite issue but rather a [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages) issue, but I'm pretty they won't do anything about it.  I'm closing this as Work as Intended.

**Closed by ghiscoding** 2024-10-21 13:29 UTC
Labels: need more info

**Comment by njfamirm** [comment] 2024-10-22 05:38
ok, thanks bro
